[build]
  publish = "."
  functions = "api"

[[redirects]]
  from = "/api/auth/callback"
  to = "/.netlify/functions/callback"
  status = 200

[[redirects]]
  from = "/Login"
  to = "/pages/auth/username.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/pages/auth/username.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/pages/dashboard/dashboard.html"
  status = 200

[[redirects]]
  from = "/links"
  to = "/pages/dashboard/links.html"
  status = 200

[[redirects]]
  from = "/link"
  to = "/pages/dashboard/links.html"
  status = 200

[[redirects]]
  from = "/customize"
  to = "/pages/dashboard/customize.html"
  status = 200

[[redirects]]
  from = "/analytics"
  to = "/pages/dashboard/analytics.html"
  status = 200

[[redirects]]
  from = "/badges"
  to = "/pages/dashboard/badges.html"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/pages/dashboard/settings.html"
  status = 200

[[redirects]]
  from = "/templates"
  to = "/pages/dashboard/templates.html"
  status = 200

[[redirects]]
  from = "/verify"
  to = "/verify.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/credits"
  to = "/credits.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/pages/profile/profile.html?user=:splat"
  status = 200
