[build]
  publish = "."

[[redirects]]
  from = "/Login"
  to = "/pages/auth/username.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/pages/auth/username.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/pages/dashboard/dashboard.html"
  status = 200

[[redirects]]
  from = "/links"
  to = "/pages/dashboard/links.html"
  status = 200

[[redirects]]
  from = "/link"
  to = "/pages/dashboard/links.html"
  status = 200

[[redirects]]
  from = "/verify"
  to = "/verify.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/pages/profile/profile.html?user=:splat"
  status = 200
